name: highly_variable_genes
description: Select highly variable genes and calculate PCA and UMAP embeddings.
keywords: [single-cell, feature-selection, pca, umap]
tools:
  - scanpy:
      description: Single-cell analysis toolkit.
      homepage: https://scanpy.readthedocs.io/
      licence: ["BSD-3-Clause"]
input:
  - - meta:
        type: map
        description: Groovy map containing sample information.
    - input_h5mu:
        type: file
        description: Input MuData object.
  - n_pcs:
      type: integer
      description: Number of principal components.
  - n_neighbors:
      type: integer
      description: Number of neighbors.
  - min_dist:
      type: float
      description: UMAP minimum distance.
output:
  h5mu:
    - - meta:
          type: map
          description: Groovy map containing sample information.
      - "*.hvg.h5mu":
          type: file
          description: MuData object with selected features and embeddings.
  umap:
    - umap_coordinates.csv:
        type: file
        description: UMAP coordinates.
  graph_umap:
    - "umap_plot_*.pdf":
        type: file
        description: UMAP plots.
  pca_gex:
    - pca_GEX.pdf:
        type: file
        description: PCA plot.
  pca_elbow:
    - pca_elbow.pdf:
        type: file
        description: PCA elbow plot.
  versions:
    - versions.yml:
        type: file
        description: Software versions.
authors: ["@nfdata-omics"]
maintainers: ["@nfdata-omics"]
